### ISSUE TITLE
When placing a bet there is an error

### ISSUE THREAD

**Issue by MichaelClarkFsu** [KPCOFGS/BetBuddy#51] opened 2024-12-05 19:42 UTC
After putting in the amount of tokens you would like to bet, an error occurs in line 310 of app.py.

This section is where the bug is:
            if user_balance and user_balance['tokenAmnt'] < bet_amount:
                # Determine the odds based on the selected team
                if team == request.form['home_team']:  # If the user selected the home team
                    odds = home_odds
                elif team == request.form['away_team']:  # If the user selected the away team
                    odds = away_odds
                else:
                    flash('Invalid team selection.', 'error')
                    return redirect(url_for('UserPage', username=user_id))

Error message: TypeError: '<' not supported between instances of 'NoneType' and 'int'

**Comment by KPCOFGS** [comment] 2024-12-05 20:48
Duplicate of #52

**Closed by KPCOFGS** 2024-12-05 20:49 UTC
